### ISSUE TITLE
Plugin is not working with Webpack 1.12.14

### ISSUE THREAD

**Issue by ManvendraSK** [vieron/stylelint-webpack-plugin#32] opened 2016-09-16 09:43 UTC
Hello,

This plugin seems not to be working. It's showing me something like following, when I console.log this:

**code**: 

``` js
const StyleLintPlugin = require('stylelint-webpack-plugin');

plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new StyleLintPlugin({configFile: '.stylelintrc', context: 'app/styles/', files: '**/*.scss', failOnError: true }),
        new webpack.DefinePlugin({
          __DEVCLIENT__: true,
          __DEVSERVER__: false
        })
    ]
```

**result**:

```
plugins:
   [ 
       HotModuleReplacementPlugin {},
       NoErrorsPlugin {},
       { apply: [Function: bound apply] },
       DefinePlugin { definitions: [Object] },
   ]
```

Even if I console.log only this plugin then it's again showing me the same result: 
**code**: `console.log(new StyleLintPlugin({configFile: '.stylelintrc', context: 'app/styles/', files: '**/*.scss', failOnError: true }));`

**result**: `{ apply: [Function: bound apply] }` 

I also looked into the implementation and found it's as per what Webpack plugin doc explains, at https://webpack.github.io/docs/plugins.html. Could you please let me know what is the fix for this?

**Comment by JaKXz** [comment] 2016-11-07 21:54
@ManvendraSK sorry for the delay, were you able to find out what the problem is?

**Comment by JaKXz** [comment] 2016-12-09 19:40
Closing for now, @ManvendraSK if you're still seeing issues please feel free to reopen with a repo that reproduces the problem. Thanks.

**Closed by JaKXz** 2016-12-09 19:40 UTC
