### ISSUE TITLE
Receiving error in files option

### ISSUE THREAD

**Issue by mikeerickson** [vieron/stylelint-webpack-plugin#16] opened 2016-07-20 22:07 UTC
I have tried several combinations:

```
files: '/**/*.css',
```

or

```
files: './src/**/*.less',
```

**Comment by mikeerickson** [comment] 2016-07-20 22:08
Here is full webpack.config.js if this will help

```
/**
 * webpack.config.js
 * Mike Erickson <codedungeon@gmail.com>
 * 2016.06.06 18:40 (mikee)
 * 2016.07.20 14:44 - mikeerickson
 * =============================================================================
 */


var path                = require('path')
var ProgressBarPlugin   = require('progress-bar-webpack-plugin')
var CopyWebpackPlugin   = require('copy-webpack-plugin');
var BuildNotifierPlugin = require('webpack-build-notifier')
var msg                 = require('gulp-messenger')
var webpack             = require('webpack')
var StyleLintPlugin     = require('stylelint-webpack-plugin');

var outputPath     = path.join(__dirname, '/dist')
var outputFilename = 'bundle.js'
var publicPath     = outputPath

var webpackConfig = {
  context: __dirname + '/src',
  devtool: 'eval', // source-map
  entry:   './index.js',
  output: {
    path:       outputPath,
    filename:   outputFilename,
    publicPath: publicPath
  },
  // devServer: {
  //   contentBase: outputPath,
  //   hot: true
  // },
  module: {
    preLoaders: [
      {test: /\.js$/, loader: "eslint-loader", exclude: /node_modules/}
    ],
    loaders: [
      {test: /\.js?$/,   loaders: ['ng-annotate', 'babel'], exclude: /node_modules/},
      {test: /\.html?$/, loaders: ['raw']},
      {test: /\.less$/,  loaders: ['style!css!less']},
      {test: /\.css$/,   loader:  "style!css"},
    ]
  },
  plugins: [

    // Display notification when build completed
    new BuildNotifierPlugin(),

    new StyleLintPlugin({
      configFile: '.stylelintrc',
      context: 'inherits from webpack',
      files: './src/**/*.less',
      failOnError: false,
    }),

    // Removes duplicate modules from the build
    new webpack.optimize.DedupePlugin(),

    // Configure ProgressBar
    new ProgressBarPlugin({
      format: msg.chalk.yellow.bold('  Building [:bar] ') + msg.chalk.green.bold(':percent') + msg.chalk.bold(' (:elapsed seconds)'),
      clear:   false,
      summary: true
    }),
    
    // Copy assets not part of bundle
    new CopyWebpackPlugin([
      { from: './index.html', to: './index.html' },
      { from: './fonts',      to: './fonts' },
      { from: './css',        to: './css' },
      { from: './data',       to: './data' },
    ]),
    
    // Compress build
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),

  ]
};

module.exports = webpackConfig;

```

**Comment by cascornelissen** [comment] 2016-07-26 12:03
This is probably caused by the (default) [webpack context](https://webpack.github.io/docs/context.html). If relative paths are ok you can just use `files: 'src/**/*.less',`.

**Comment by JaKXz** [comment] 2016-09-29 04:22
@mikeerickson sorry for the delayed response, but @cascornelissen's suggestion would be what I would suggest. Is this still an issue for you?

**Comment by JaKXz** [comment] 2016-11-16 00:02
@mikeerickson I'm going to close this for now, the documentation was improved recently in #36. Hope this isn't an issue for you anymore!

**Closed by JaKXz** 2016-11-16 00:02 UTC
